apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-nginx
  name: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}