{{- if .Values.ingress.enabled  }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Release.Name }}-nginx
spec:
  rules:
    - host: {{ .Values.ingress.exrernalName }}
      http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}-nginx
              servicePort: 80
            path: /
{{- end -}}